# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    admin.post:
        class: Admin\AdminBundle\Admin\PostAdmin
        arguments: [~, Admin\AdminBundle\Entity\Post, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Post }