services:
    app.admin.post:
        class: Admin\AdminBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Post" }
        arguments:
            - ~
            - Admin\AdminBundle\Entity\Post
            - ~
        calls:
            - [ setTranslationDomain, [AdminAdminBundle]]

